# ── Global ────────────────────────────────────────────────────────────────────
windowrule = match:class .*, suppress_event maximize

# ── XWayland Video Bridge ─────────────────────────────────────────────────────
windowrule = match:class ^(xwaylandvideobridge)$, no_screen_share 1
windowrule = match:class ^(xwaylandvideobridge)$, no_blur 1
windowrule = match:class ^(xwaylandvideobridge)$, no_anim 1
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus 1
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1
windowrule = match:class ^(xwaylandvideobridge)$, suppress_event activate
windowrule = match:class ^(xwaylandvideobridge)$, suppress_event activatefocus

# ── Gamescope ─────────────────────────────────────────────────────────────────
windowrule = match:class ^(gamescope)$, float 1
windowrule = match:class ^(gamescope)$, size 2560 1440
windowrule = match:class ^(gamescope)$, center 1
windowrule = match:class ^(gamescope)$, monitor 0
windowrule = match:class ^(gamescope)$, fullscreen 1
