windowrule = match:class .*, suppress_event maximize
# completely hide it
windowrule = match:class ^(xwaylandvideobridge)$, no_screen_share 1

# remove blur
windowrule = match:class ^(xwaylandvideobridge)$, no_blur 1

# disable animations
windowrule = match:class ^(xwaylandvideobridge)$, no_anim 1

# don't focus initially
windowrule = match:class ^(xwaylandvideobridge)$, no_initial_focus 1

# force a tiny max size so it doesn’t steal space
windowrule = match:class ^(xwaylandvideobridge)$, max_size 1 1

# suppress all focus activate events too (optional, useful for some capturers)
windowrule = match:class ^(xwaylandvideobridge)$, suppress_event activate, suppress_event activatefocus

